---

# Deletes all AMIs, except the one specified
# Inputs:
# - aws_ami_cleanup_amis: list of matching AMI objects
# - aws_ami_cleanup_exclude_ami_id: the AMI ID to exclude from cleanup
# - aws_ami_cleanup_region: AWS region
# Outputs: None

- name: Delete AMIs
  amazon.aws.ec2_ami:
    state: absent
    wait: no
    delete_snapshot: yes
    image_id: "{{ item.image_id }}"
    region: "{{ aws_ami_cleanup_region }}"
  with_items: "{{ aws_ami_cleanup_amis.images }}"
  when: item.image_id != aws_ami_cleanup_exclude_ami_id
