---

- hosts: localhost
  roles:
    - {
        role: aws-vpc,
        aws_vpc_region: "{{ aws_region }}"
      }
    - {
        role: aws-ami-lookup,
        owner_account_id: self,
        filter_by_name: "base-*"
      }
    - {
        role: aws-ec2,
        ami_id: "{{ aws_ami_lookup_ami.image_id }}",
        instance_tags: {"Name": "bastion"},
        instance_type: "t3.nano",
        count: 1,
        vpc_subnet_id: "{{ aws_vpc_output.stack_outputs.PublicSubnetDId }}",
        security_group_id: "{{ aws_vpc_sg_output.stack_outputs.BastionSgId }}",
        region: "{{ aws_region }}"
      }

- hosts: localhost
  tasks:
    - name: Refresh inventory
      meta: refresh_inventory

- hosts: tag_Name_bastion
  roles:
    - bastion
