---

# AWS ALB and ASG for web
# Inputs:
# - web_app_alb_sg_ids
# - web_app_alb_subnet_ids
# - web_app_ami_id
# - web_app_asg_cpu_scaling_threshold
# - web_app_initial_setup
# - web_app_instance_type
# - web_app_instances_desired
# - web_app_instances_max
# - web_app_instances_min
# - web_app_preview: (boolean) when true and used with an existing stack, will generate changeset only
# - web_app_region
# - web_app_server_sg_ids
# - web_app_vpc_id
# Outputs:
# - aws_web_app_output
#     WebAutoScalingGroupId
#     WebLaunchTemplateDefaultVersion
#     WebLaunchTemplateId
#     WebLaunchTemplateLatestVersionNumber
#     WebListenerHttpArn
#     WebListenerHttpId
#     WebLoadBalancerDnsName
#     WebLoadBalancerFullName
#     WebLoadBalancerHostedZoneId
#     WebLoadBalancerId
#     WebLoadBalancerName
#     WebTargetGroupFullName
#     WebTargetGroupId
#     WebTargetGroupName

- name: Web app via CloudFormation
  amazon.aws.cloudformation:
    create_changeset: "{{ web_app_preview }}"
    region: "{{ web_app_region }}"
    stack_name: "web-app-use1"
    state: "present"
    template: "roles/web-app/files/cloudformation-{{ web_app_region }}-app.yml"
    template_parameters:
      AlbSecurityGroupIds: "{{ web_app_alb_sg_ids }}"
      AlbSubnetIds: "{{ web_app_alb_subnet_ids }}"
      AmiId: "{{ web_app_ami_id }}"
      InitialSetupNoHttps: "{{ web_app_initial_setup }}"
      InstanceIAMManagedPolicyName: "web-app"
      InstanceIAMProfileName: "web-app"
      InstanceIAMRoleName: "web-app"
      InstanceType: "{{ web_app_instance_type }}"
      InstancesDesired: "{{ web_app_instances_desired }}"
      InstancesMax: "{{ web_app_instances_max }}"
      InstancesMin: "{{ web_app_instances_min }}"
      ParameterStorePath: "/production/web-app/*"
      ScalingCpuUtilizationThreshold: "{{ web_app_asg_cpu_scaling_threshold }}"
      ServerSecurityGroupIds: "{{ web_app_server_sg_ids }}"
      VpcId: "{{ web_app_vpc_id }}"
  register: aws_web_app_output

- name: Web app output
  debug:
    msg: "{{ aws_web_app_output.stack_outputs }}"

- name: Web app changeset
  debug:
    msg: "{{ aws_web_app_output.change_set_id }}"
  when: aws_web_app_output.change_set_id is defined
