---

# Terminates EC2 instances with the given name
# Inputs:
# - aws_ec2_terminate_instance_name: value of the Name tag of the EC2 instances to terminate
# - region: AWS region of the instance
# Outputs: None

- name: Find the EC2 instance IDs
  ec2_instance_info:
    filters:
      "tag:Name": "{{ aws_ec2_terminate_instance_name }}"
      instance-state-name: [ "running", "stopped" ]
  register: ec2_instances

- name: Terminate instance
  amazon.aws.ec2:
    state: 'absent'
    instance_ids: "{{ item.instance_id }}"
    region: "{{ region }}"
  with_items: "{{ ec2_instances.instances }}"
