---

# Launches EC2 instance with specified AMI, or makes sure it exists
# Inputs:
# - ami_id
# - instance_tags: A dictionary of tags to attach to the EC2 instance(s)
# - instance_type
# - count: Number of EC2 instance(s)
# - count_filters: A dictionary of filters to use for counting
# - vpc_subnet_id
# - security_group_id
# - region
# Outputs:
# - ec2

- name: Launch instance
  amazon.aws.ec2_instance:
    key_name: default
    instance_type: "{{ instance_type }}"
    image_id: "{{ ami_id }}"
    wait: yes
    exact_count: "{{ count }}"
    filters: "{{ count_filters }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    security_group: "{{ security_group_id }}"
    region: "{{ region }}"
    network:
      assign_public_ip: yes
    tags: "{{ instance_tags }}"
  register: ec2

- name: Wait for SSH to come up
  delegate_to: "{{ item.public_ip_address }}"
  wait_for_connection:
    delay: 30
    sleep: 5
    timeout: 320
  loop: "{{ ec2.instances }}"
